name: Add Artist
description: Submit a new artist to the index
title: "https://open.spotify.com/artist/..."
labels: ["add-artist"]
body:
  - type: markdown
    attributes:
      value: "**Replace the issue title above with the Spotify artist URL.**"

  - type: dropdown
    id: disclosed
    attributes:
      label: Has the artist disclosed AI usage?
      options:
        - "Yes"
        - "No"
    validations:
      required: true

  - type: checkboxes
    id: disclosure_types
    attributes:
      label: Where is AI used?
      description: Leave blank if unclear or if you are unsure
      options:
        - label: Instrumentation
        - label: Lyrics
        - label: Mastering
        - label: Mixing and/or Production
        - label: Vocals

  - type: markdown
    attributes:
      value: "## Evidence URLs"

  - type: input
    id: url_1
    attributes:
      label: URL 1
      description: Link to evidence (spotify profile, instagram, album on deezer, article, social media post, etc.)
      placeholder: https://...
    validations:
      required: true

  - type: textarea
    id: notes_1
    attributes:
      label: Notes 1
      description: Context or comments for URL 1. Please paste in the direct quotes if possible.
      render: text
    validations:
      required: true

  - type: input
    id: url_2
    attributes:
      label: URL 2
      placeholder: https://...
    validations:
      required: false

  - type: textarea
    id: notes_2
    attributes:
      label: Notes 2
      description: Context or comments for URL 2. Please paste in the direct quotes if possible.
      render: text
    validations:
      required: false

  - type: input
    id: url_3
    attributes:
      label: URL 3
      placeholder: https://...
    validations:
      required: false

  - type: textarea
    id: notes_3
    attributes:
      label: Notes 3
      description: Context or comments for URL 3. Please paste in the direct quotes if possible.
      render: text
    validations:
      required: false

  - type: checkboxes
    id: markers
    attributes:
      label: Markers
      description: |
        2024-onwards = Artist emerged in 2024 or later 路 ai-visuals = Uses AI-generated visual content 路 anonymous = No clear public identity 路 high-output = Unusually high volume of releases 路 inconsistent-style = Inconsistent styles, vocals etc across catalog
      options:
        - label: 2024-onwards
        - label: ai-visuals
        - label: anonymous
        - label: high-output
        - label: inconsistent-style

  - type: markdown
    attributes:
      value: "## Socials"

  - type: input
    id: youtube
    attributes:
      label: YouTube
      placeholder: https://www.youtube.com/channel/...
    validations:
      required: false

  - type: input
    id: apple_music
    attributes:
      label: Apple Music
      placeholder: https://music.apple.com/artist/...
    validations:
      required: false

  - type: input
    id: amazon_music
    attributes:
      label: Amazon Music
      placeholder: https://music.amazon.com/artists/...
    validations:
      required: false

  - type: input
    id: tiktok
    attributes:
      label: TikTok
      placeholder: https://www.tiktok.com/@...
    validations:
      required: false

  - type: input
    id: instagram
    attributes:
      label: Instagram
      placeholder: https://www.instagram.com/...
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other relevant information about this artist that supports your submission.
      render: text
    validations:
      required: false
